<?php
/**
 * @var \Billmate\BillmateCheckout\Block\Info $block
 * @see \Billmate\BillmateCheckout\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
$bmInvoiceId = $block->getBmInvoiceId();
?>
<dl class="payment-method">
    <dt class="title"><?= /* @noEscape */ $title ?></dt>
    <?php if ($specificInfo) : ?>
        <dd class="content">
            <table class="data table">
                <caption class="table-caption"><?= /* @noEscape */ $title ?></caption>
                <?php foreach ($specificInfo as $label => $value) : ?>
                    <tr>
                        <th scope="row"><?= $block->escapeHtml($label) ?></th>
                        <td>
                            <?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </dd>
    <?php endif;?>
</dl>
<?= $block->getChildHtml() ?>
<div class="payment-method-description">
    <div class="order-payment-method-title">
        <?= __('Type of payment: <b>%1</b>', $block->getMethodDescription()) ?>
    </div>
    <?php if ($bmInvoiceId): ?>
        <div class="order-payment-invoice-id">
            <?= __('Billmate Invoice Id:  <b>%1</b>', $bmInvoiceId) ?>
        </div>
    <?php endif; ?>
</div>


