<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Billmate\BillmateCheckout\Block\Adminhtml\Order\View\InvoiceFee */

$_order     = $block->getOrder();
?>
<tr>
    <td class="label">
        <div>
                <?= $block->escapeHtml(__('Billmate Invoice Fee')) ?>
        </div>
    </td>
    <td>
        1234
    </td>
</tr>
