<?php
/**
 * Shopping cart content template
 *
 * @var $block \Billmate\BillmateCheckout\Block\Checkout\Items
 */
?>
<?php $items = $block->getItems() ?>
<?php $shippingMethodsRates = $block->getShippingMethodsRates() ?>
<?php $isEnabledButtons = $block->isEnabledButtons() ?>
<div class="bm-checkout-shopping-cart">
    <h2><?= __('Shopping Cart') ?></h2>
    <div class="table-responsive">
        <div class="billmate-checkout-cart-table">
            <div class="billmate-checkout-table-head">
                <div class="billmate-checkout-product-head"><?= __('Product') ?></div>
                <div class="billmate-checkout-price-head"><?= __('Price') ?></div>
                <div class="billmate-checkout-qty-head"><?= __('Quantity') ?></div>
                <div class="billmate-checkout-sum-head"><?= __('Sum') ?></div>
            </div>
            <?php foreach ($items as $item) : ?>
                <span id="billmate-checkout-line" class="billmate-checkout-line"></span>
                <div class="billmate-checkout-product-row">
                    <div class="billmate-checkout-img">
                        <?= $block->getImage($item->getProduct(), 'billmate_checkout_content')->toHtml() ?>
                    </div>
                    <div class="billmate-checkout-name">
                        <p><?= $block->escapeHtml($item->getName()) ?></p>
                        <?php if($block->isShowAttribute()): ?>
                            <div class="bm-options-wrapper">
                                <?php if ($_options = $block->getProductOptions($item)):?>
                                    <dl class="item-options">
                                        <?php foreach ($_options as $_option) : ?>
                                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                            <dd>
                                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                                    <?= /* @escapeNotVerified */ $_formatedOptionValue['full_view'] ?>
                                                <?php else: ?>
                                                    <?= /* @escapeNotVerified */ $_formatedOptionValue['value'] ?>
                                                <?php endif; ?>
                                            </dd>
                                        <?php endforeach; ?>
                                    </dl>
                                <?php endif;?>
                            </div>
                        <?php  endif; ?>
                    </div>
                    <div class="billmate-checkout-price" id="price_<?= $item->getId() ?>"><?= $block->formatPrice($block->displayPricesIncludeTax()? $item->getPriceInclTax() : $item->getPrice()) ?></div>
                    <div class="billmate-checkout-qty <?= !$isEnabledButtons? 'no-buttons' : '' ?>" id="qty_<?= $item->getId() ?>">
                        <?php if($isEnabledButtons): ?>
                            <button class="billmate-checkout-button-sub sub" id="bm-sub-btn sub_<?= $item->getId() ?>" name="sub">
                            <span class="action-sign-decr">
                                &#8211;
                            </span>
                            </button>
                        <?php endif ?>
                        <div class="billmate-checkout-product-qty"><?= $item->getQty() ?></div>
                        <?php if($isEnabledButtons): ?>
                            <button id="bm-inc-btn inc_<?= $item->getId() ?>" class="billmate-checkout-button-inc inc" name="inc">
                            <span class="action-sign-inc">
                                &#43;
                            </span>
                            </button>
                        <?php endif ?>
                    </div>
                    <div class="billmate-checkout-sum" id="sum_<?= $item->getId() ?>"><?= $block->formatPrice($block->displayPricesIncludeTax()? $item->getRowTotalInclTax() : $item->getRowTotal()) ?></div>
                    <div class="billmate-checkout-del-but">
                        <span id="bm-del-btn del_<?= $item->getId() ?>" class="billmate-checkout-button-del del" name="del"></span>
                    </div>
                    <span id="billmate-checkout-line" class="billmate-checkout-line"></span>
                </div>

            <?php endforeach; ?>
        </div>
    </div>
</div>
