<?php
/**
 * @var $block \Billmate\BillmateCheckout\Block\Checkout\Totals
 */
?>
<div class="bm-checkout-totals">
    <h1><?= __('Totals') ?></h1>
    <table>
        <tr>
            <td class="name"><?= __('Shipping') ?></td><td class="price"><?= $block->formatPrice($block->getShippingValue()) ?></td>
        </tr>
        <tr>
            <?php if($this->hasDiscount()): ?>
            <td class="name"><?= __('Discount') ?></td>
            <td class="price"><?= $block->formatPrice($block->getDiscountValue()) ?></td>
        </tr>
        <tr>
            <?php endif ?>
            <td class="name"><?= __('Tax') ?></td><td class="price"><?=  $block->formatPrice($block->getTaxValue()) ?></td></tr><tr>
            <td class="name"><?= __('Total') ?></td><td class="price"><?= $block->formatPrice($block->getTotalValue()) ?></td>
        </tr>
    </table>
</div>